### ISSUE TITLE
B1修改建议

### ISSUE THREAD

**Issue by JasonSi** [cdf2/web_tasks#2]
- 添加留言应该是get '/add'后进入有输入框的页面，post '/add'响应提交。
- 添加成功留言后应该直接跳转到主页，可以使用redirect to之类的方式，而不是手动返回还要手动刷新
- 添加失败留言也是，不应该让用户手动返回，应该提交后，服务器判定失败，存下用户提交的数据，然后重新渲染erb（不是跳转），并且把之前存的数据填上，不能让用户白写。
- 按时间倒序排列，后添加的放在前面
- 筛选功能呢？
- 任务明确规定了删除的路由是 get '/delete/:id' 请修改

总的来说，虽然离检查点差了一些，但是的确挺认真的，做得也很不错，按照上面建议修改一下吧。

**Comment by JasonSi** [comment]
... 要添加留言，get '/add'这个只要一个 a标签就可以了，怎么造了个表单。。。这很不合理
查询的功能比要求的扩展了，但是严格说没有达到要求。

其余还是很不错的，继续加油吧～

**Comment by cdf2** [comment]
多谢学长，已经改了一下了
